- hosts: localhost
  vars:
      destination_host: <host>.deployment.goldengate.eu-frankfurt-1.oci.oraclecloud.com/services/v2
      #extract name
      extract: EXT1
      #replicat name
      replicat: REP1
  tasks:
      - name: DELETE EXTRACT
        uri:
            url: https://{{ destination_host }}/extracts/{{ extract }}
            url_username: oggadmin
            url_password: <password>
            method: DELETE
        ignore_errors: yes
        register: rest_post
      - name: DEBUG / GOT INFO
        debug:
            msg: "{{ rest_post.json }}"
        when: rest_post.status ==  200
      - name: DELETE replicat
        uri:
            url: https://{{ destination_host }}/replicats/{{ replicat }}
            url_username: oggadmin
            url_password: <password>
            method: DELETE
        ignore_errors: yes
        register: rest_delete
      - name: DEBUG / GOT INFO
        debug:
            msg: "{{ rest_delete.json }}"
        when: rest_delete.status ==  200
      - name: CREATE EXTRACT
        uri:
            url: https://{{ destination_host }}/extracts/{{ extract }}
            url_username: oggadmin
            url_password: <password>
            method: POST
            body_format: json
            body:
                config: ["Extract EXT1","ExtTrail a1","UseridAlias <alias> DOMAIN <domain>","Table <user>.<table>;"]
                source: {"tranlogs":"integrated"}
                credentials: {"alias":"<alias>","domain":"<domain>"}
                begin: "now"
                targets: [{"name":"a1"}]
        ignore_errors: yes
        register: rest_post
      - name: DEBUG / GOT INFO
        debug:
            msg: "{{ rest_post.json }}"
        when: rest_post.status ==  201
      - name: CREATE replicat
        uri:
            url: https://{{ destination_host }}/replicats/{{ replicat }}
            url_username: oggadmin
            url_password: <password>
            method: POST
            body_format: json
            body:
                config: ["Replicat {{ replicat }}","UseridAlias <alias> DOMAIN <domain>","Map <user>.<table>,","Target <user>.<table>;"]
                source: {"name":"a1"}
                credentials: {"alias":"<alias>","domain":"<domain>"}
                checkpoint: {"table":"<user>.<CHECKPOINTABLE>"}
                mode: {"type": "nonintegrated"}
        ignore_errors: yes
        register: rest_post
      - name: DEBUG / GOT INFO
        debug:
            msg: "{{ rest_post.json }}"
        when: rest_post.status ==  201
