- name: Register Oracle Database
  hosts: localhost
  collections:
    - oracle.oci
  vars:
    #ansible_python_interpreter: /usr/bin/python3
  tasks:
   - name: Create database_registration
     oci_golden_gate_database_registration:
      display_name: dbaas
      compartment_id: "ocid1.compartment.oc1..aaa........"
      fqdn: <name>.subnet.vcn.oraclevcn.com
      username: <gg db user>
      password: <password>
      connection_string: <name>.subnet.vcn.oraclevcn.com:1521/<CDB>.subnet.vcn.oraclevcn.com
      alias_name: my_dbaas
      ip_address: <database ip>
      subnet_id: ocid1.subnet.oc1.eu-frankfurt-1.subenetid..........
