- hosts: localhost
  vars:
      destination_host: <GG instance>/services/v2/extracts
      #Extract name
      extract: EXT1
  tasks:
      - name: CREATE EXTRACT
        uri:
            url: https://{{ destination_host }}/{{ extract }}
            url_username: oggadmin
            url_password: <Password>
            method: POST
            body_format: json
            body:
                # Parameters of Extract
                config: ["Extract <Extract name>","ExtTrail <trail file>","UseridAlias <your alias> DOMAIN <Your domain>","Table <schema>.<table>;"]
                source: {"tranlogs":"integrated"}
                credentials: {"alias":"<your alias>","domain":"<Your domain>"}
                begin: "now"
                targets: [{"name":"<trail file>"}]
        ignore_errors: yes
        register: rest_post
      - name: DEBUG / GOT INFO
        debug:
            msg: "{{ rest_post.json }}"
        when: rest_post.status ==  201
