#The first line you define the name of this play
#The second the machine where is going to connect. In this case, it's localhost
#The third line the collection we need to run our tasks.
- name: Create OCI GoldenGate Deployment
  hosts: localhost
  collections:
    - oracle.oci
  vars:
    #ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: Create GoldenGate Deployment
      oci_golden_gate_deployment:
        display_name: MyGGDeployment
        license_model: BRING_YOUR_OWN_LICENSE
        compartment_id: >-
          ocid1.compartment.oc1..aaa....
        subnet_id: >-
          ocid1.subnet.oc1.eu-frankfurt-1.a....
        cpu_core_count: 1
        is_auto_scaling_enabled: true
        is_public: true
        deployment_type: OGG
        ogg_data:
          admin_username: oggadmin
          admin_password: '<password>'
          deployment_name: MyGGDeployment1
